name: Windows

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Command (powershell)'
        required: true
      pincode:
        description: 'Pin (6 digits)'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing CRD
      run: ./windows/crd.msi
    - name: Installing Chrome
      run: ./windows/chrome.exe /install
    - name: Changing Resolution
      run: ./windows/qres.exe /x:1920 /y:1080
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Running
      run: ./windows/kr.ps1
